# Generated by Django 4.1.3 on 2022-11-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theaters', '0001_initial'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTheaterTicket',
            fields=[
                ('theater_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('movie_showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showtimes.movieshowtime')),
                ('movie_theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.movietheater')),
            ],
            options={
                'db_table': 'movie_theater_tickets',
            },
        ),
    ]
